### ISSUE TITLE
First Thread

### ISSUE THREAD

**Issue by Drflash55** [Apostolique/AposFeedingBot#1]
This is not really an issue, just a little thread saying that I am looking forward to seeing how you will go with this...
I will be surprised if it can surpass the Raga Minions, because that's a true Feeding Bot.

**Comment by Apostolique** [comment]
With enough proxies, you can beat Raga Minions. I assume that's how they do it?

**Comment by henopied** [comment]
They likely connect using a websocket directly to the server to minimize overhead.
