### ISSUE TITLE
Split danger

### ISSUE THREAD

**Issue by henopied** [Apostolique/AposFeedingBot#3]
It would seem that once the bot it put in slave mode it doesn't always identify split predictors when it should I pressed m a couple times and it changed from danger to split danger multiple times

**Comment by Drflash55** [comment]
Maybe it was not programmed that way? Not sure why it acts like that.

**Comment by Apostolique** [comment]
I did that on purpose. At saves a lot of time in order to reach the destination. Sure it can get split on, but usually at size 50, the trade off is worth it. And really, if you're going to have an army of small bots, even if a few get eaten, it's still fine.

**Comment by henopied** [comment]
seems strange..

**Comment by henopied** [comment]
Alright then
