### ISSUE TITLE
How do I get this to work?

### ISSUE THREAD

**Issue by ghost** [Apostolique/AposFeedingBot#6]
I put two tabs open one agar.io bot is master the other is slave I left them and the slave NEVER went into the MASTER??????????? I was hoping I just found the FIRST free hack but idk if this works any more! Plz fix or explain how it works!

**Comment by henopied** [comment]
Get your own parse a account and change the feeding bot script to use your parse account and make sure when you put them on the party server that they are all infact on the same ip and port

**Comment by Apostolique** [comment]
The problem is that you used tabs. You need to make the tabs be their own window.

**Comment by ghost** [comment]
How do i make a parse account? Sorry I am asking so many questions! Thx for responding tho!

**Comment by Apostolique** [comment]
You don't need a parse account if you just make the bot be it's own window.

**Comment by ghost** [comment]
Ohh! Ok then! Thx!!!!!!!!!!!!!

On Thu, Sep 24, 2015 at 1:06 PM, Jean-David Moisan <notifications@github.com
